# Setup
title: Oak nut
description: I do science, I do code, I do a little bit of everything—because why not?
url: https://Oak-nut.github.io
avatar: /avatar.jpg
paginate: 5
permalink: 
cover_image: /bg.jpeg

# Gems
plugins:
  - jekyll-remote-theme

remote_theme: vszhub/not-pure-poole

# Optimize Jekyll
exclude:
  - .editorconfig
  - .git
  - .jekyll-cache
  - Gemfile
  - Gemfile.lock
  - LICENSE.md
  - README.md
  - scripts/
  - not-pure-poole.gemspec

# Optimize Jekyl SEO Tag
logo: logo.png
social:
  name: Muqing Yang
  links:
    - https://github.com/Oak-nut
    - https://www.linkedin.com/in/muqingyang
    - mailto:ymqdmail@gmail.com
google_site_verification: 
lang: en

sass:
  sass_dir: _sass
  style: :compressed

navigation:
  - title: Introduction
    url: /resume/

# Options

# Replace this value and uncomment to enable Google Analytics tracking
# google_analytics: UA-000000-0

# Replace this value and uncomment to enable Disqus
# disqus: xxxxxx

# Specify the author for blog posts
author:
  name: Muqing Yang
  url: https://github.com/Oak-nut
  email: ymqdmail@gmail.com
